---
title: "Covid-19 Positive Tests by Local Authority"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

<style>                     
.navbar {
  background-color:#00ad93;
  border-color:black;
}
</style> 

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggdark)
library(DT)
library(plotly)
library(ggrepel)
library(shiny)

today_date <- Sys.Date()

my_drive <- ""

df <- read.csv(paste0(my_drive, "coronavirus-cases_latest.csv")) 

df <- df %>%
  mutate_at('Specimen.date', ~ as.Date(.)) %>%
  filter(Area.type == "Upper tier local authority") %>%
  select("Area.name", "Area.code","Specimen.date", "Daily.lab.confirmed.cases", "Cumulative.lab.confirmed.cases", "Cumulative.lab.confirmed.cases.rate") %>% 
  rename(
    "area" = `Area.name`,
    "code" = `Area.code`,
    "date" = `Specimen.date`, 
    "daily_cases" = `Daily.lab.confirmed.cases`, 
    "cumulative_cases" = `Cumulative.lab.confirmed.cases`, 
    "cases_rate" = `Cumulative.lab.confirmed.cases.rate`
  )

recent_week_all_df <- df %>% filter(date >= today_date -9 & date <= today_date - 3) %>%
  group_by(area) %>% 
  summarise(cases=sum(daily_cases)) %>% 
  arrange(desc(cases)) 

previous_week_all_df <- df %>% filter(date >= today_date -16 & date <= today_date - 10) %>%
  group_by(area) %>% 
  summarise(cases=sum(daily_cases)) %>% 
  arrange(desc(cases)) 

names(previous_week_all_df) <- c("area", "previous_week_cases")


df_joined <- left_join(recent_week_all_df, previous_week_all_df) %>%
  mutate(change = cases - previous_week_cases)

make_hist <- function(df) {
  df %>%
    ggplot(
      aes(
        date, 
        daily_cases, 
        text = 
          paste(
            paste0('Local Authority: ', area),
            '\n',
            paste0('Day: ', date),
            '\n',
            paste0('Number of cases on that day: ', daily_cases)
          ),
        alpha = 0.5
      )
    ) +
    geom_bar(stat = "identity", position = "identity", fill = "#00ad93") +
    theme_bw() +
    theme(
      legend.position = 'none',
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
    ) + 
    xlab('') + 
    ylab('Daily cases')
}


df_latest <- df %>% filter(date == max(date)) %>% arrange(desc(cumulative_cases)) %>% head(20)

chart_max <- round(max(df_latest$cumulative_cases), -3)

make_bar <- function(df, key_var, chart_title){
  df %>%
  ggplot(aes(x = reorder(area, df[[key_var]]), y = df[[key_var]])) +
  geom_bar(stat = "identity", fill  = "#00ad93", width = 0.8) +
  scale_y_continuous(breaks = seq(0, chart_max, by = chart_max/10)) +
  coord_flip() +
  labs(x = "Local Authority", y = "Cases", 
       title = chart_title) +
  theme(axis.text.x = element_text(angle = 45)) +
  theme(axis.title = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 11, face = "bold")) +
  theme_minimal()
}
  
bar1 <- make_bar(df_latest, "cumulative_cases", "Cases across the pandemic")

recent_week_df <- df %>% filter(date >= today_date -9 & date <= today_date - 3) %>%
  group_by(area) %>% 
  summarise(cases=sum(daily_cases)) %>% 
  arrange(desc(cases)) %>%
  head(20)

chart_max <- round(max(recent_week_df$cases), -2)

bar2 <- make_bar(recent_week_df, "cases", paste("Cases between", 
                                                  format(today_date -9,"%a %b %d"),
                                                  "and", 
                                                  format(today_date -3,"%a %b %d")
                                                  ))

scatter <- ggplot(df_joined, aes(x = cases, y = change)) +
  geom_point(colour = "#00ad93", fill = "#00ad93", size = df_joined$cases/50) +
  labs(title= "Cases last week vs. change prevous week",
       subtitle = "",
       caption = "",
       x = "Cases last week",
       y = "Change since previous week") +
  theme_minimal() +
  geom_text_repel(aes(label = ifelse(abs(change) > 20, area,'')),
                  box.padding   = 0.05,
                  point.padding = 0.5,
                  force = 10,
                  segment.color = 'black',
                  colour = 'black')

histogram_app <- shinyApp(
  ui = fluidPage(    
    
    # Give the page a title
    titlePanel('Histogram of daily positive Covid-19 tests by Local Authority'),
    
    # Generate a row with a sidebar
    sidebarLayout(      
      
      # Define the sidebar with one input
      sidebarPanel(
        selectInput("area", "Local Authority:", 
                    choices = sort(unique(df$area))),
        hr()
      ),
      
      # Create a spot for the barplot
      mainPanel(
        plotOutput("daily_cases_hist")  
      )
    )
  ), 
  server = function(input, output) {
    
    # Fill in the spot we created for a plot
    output$daily_cases_hist <- renderPlot({
      
      df %>%
        filter(
          area == input$area
        ) %>%
        make_hist
    })
  }
)

```
Daily Cases Over Time
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------

### All Local Authorities

```{r}
histogram_app
```


Most Positive Tests 
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------


### Across Pandemic
```{r}
ggplotly(bar1)
```

### Last week 
```{r}
ggplotly(bar2)
```

Recent Change
=======================================================================

Column {.tabset}
-----------------------------------------------------------------------


### Cases last week vs. change previous week
```{r}
scatter
```


About
=======================================================================

**PHE Postive Tests by Local Authority**

Last updated: `r today_date`

To follow

**Data**
PHE coronvirus dashboard
